
@endpoint = 5mdj6w8cwk.execute-api.eu-west-3.amazonaws.com/prod/receiveData
@cloudfront = d38yzyxxnty5po.cloudfront.net
//d25duxanbi4pts.cloudfront.net

GET {{cloudfront}}?data=Nami
###

POST {{cloudfront}}
Content-Type: application/x-www-form-urlencoded

PASSKEY=599E78B1B5EA0911BF1EE9940954FFA2&stationtype=EasyWeatherPro_V5.1.1&runtime=2&dateutc=2023-04-24+23:13:44&tempinf=65.7&humidityin=42&baromrelin=29.926&baromabsin=26.164&tempf=49.3&humidity=75&winddir=178&windspeedmph=0.00&windgustmph=0.00&maxdailygust=1.12&solarradiation=0.00&uv=0&rainratein=0.000&eventrainin=0.000&hourlyrainin=0.000&dailyrainin=0.000&weeklyrainin=0.012&monthlyrainin=0.272&yearlyrainin=7.201&totalrainin=7.201&wh65batt=0&freq=868M&model=WS2900_V2.01.18&interval=10
###

//Invalid station
POST {{cloudfront}}
Content-Type: application/x-www-form-urlencoded

PASSKEY=1234&stationtype=EasyWeatherPro_V5.1.1&runtime=4&dateutc=2023-04-24+23:45:05&tempinf=66.2&humidityin=42&baromrelin=29.923&baromabsin=26.161&tempf=48.6&humidity=74&winddir=280&windspeedmph=0.22&windgustmph=1.12&maxdailygust=1.12&solarradiation=0.00&uv=0&rainratein=0.000&eventrainin=0.000&hourlyrainin=0.000&dailyrainin=0.000&weeklyrainin=0.012&monthlyrainin=0.272&yearlyrainin=7.201&totalrainin=7.201&wh65batt=0&freq=868M&model=WS2900_V2.01.18&interval=10
###
POST {{cloudfront}}
Content-Type: application/json

{   
    "PASSKEY": "599E78B1B5EA0911BF1EE9940954FFA2",
    "stationtype": "EasyWeatherPro_V5.1.1",
    "runtime": "2",
    "dateutc": "2023-04-24 23:13:44",
    "tempinf": "65.7",
    "humidityin": "42",
    "baromrelin": "29.926",
    "baromabsin": "26.164",
    "tempf": "49.3",
    "humidity": "75",
    "winddir": "178",
    "windspeedmph": "0.00",
    "windgustmph": "0.00",
    "maxdailygust": "1.12",
    "solarradiation": "0.00",
    "uv": "0",
    "rainratein": "0.000",
    "eventrainin": "0.000",
    "hourlyrainin": "0.000",
    "dailyrainin": "0.000",
    "weeklyrainin": "0.012",
    "monthlyrainin": "0.272",
    "yearlyrainin": "7.201",
    "totalrainin": "7.201",
    "wh65batt": "0",
    "freq": "868M",
    "model": "WS2900_V2.01.18",
    "interval": "10",
    "spainTime": "20230514133316"
}
###

GET {{cloudfront}}?station_id=Nami&station_key=Itachi
###

POST {{cloudfront}}
Content-Type: application/x-www-form-urlencoded

location=Galve&service=myservice&station_id=Nami&station_key=Itachi
###

POST {{cloudfront}}
Content-Type: application/json

{   
    "PASSKEY": "123456789",
    "location": "Laura",
    "service": "yoMisma"
}
###

POST {{endpoint}}/
Content-Type: application/json

{
    "location": "Royo"
}
###
POST {{endpoint}}/receiveData/
Content-Type: application/json

{
    "location": "Lua"
}
###
GET {{endpoint}}/receiveData/spaceId=7379560b-e399-4d8e-92ee-313ceeacdfa1
###


GET {{endpoint}}/receiveData?location=Nami
###
